"""empty message

Revision ID: 907747cb0eb9
Revises: f3b00642b778
Create Date: 2024-02-23 18:09:22.508984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907747cb0eb9'
down_revision = 'f3b00642b778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
